cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
branches:
  only:
    - master
before_script:
  - git config --global user.email "test@example.com"
  - git config --global user.name "test user"
script:
  - bundle exec rake
